# Site settings
title: CITY OF CLEVELAND POLICE DEPARTMENT
email: 
description: > # this means to ignore newlines until "baseurl:"
  Keeping Cleveland Safe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mariakuz.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

#redcarpet:
 # extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
